### ISSUE TITLE
Any plan to put it on HomeBrew?

### ISSUE THREAD

**Issue by lsanotes** [guumaster/hostctl#13]

**Comment by guumaster** [comment]
I'd like that. But I don't have a mac and never used `brew` before,  so I'd be hard to test it for me. 

I'll check how it is done and try to do it. Of course, this is open for PRs too.

**Comment by guumaster** [comment]
@lsanotes I've added a "Brew Tap" to the GoReleaser script. But I don't have `brew` to test it. 

You can help with it by adding a comment (or PR!) with the steps to do it. Report it here or in #14, that is created specifically for installations.

Thanks!

**Comment by pacodes** [comment]
@guumaster This is brew install output
```
brew install --verbose --debug hostctl
Error: No available formula with the name "hostctl" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.11\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.4\)\ curl/7.64.1 --retry 3 --location https://api.github.com/search/code\?q=user\%3AHomebrew\+path\%3AFormula\+path\%3ACasks\+path\%3A.\+filename\%3Ahostctl\+extension\%3Arb\&per_page=100 --header Accept:\ application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --header Accept:\ application/vnd.github.antiope-preview\+json --dump-header /private/tmp/github_api_headers20200326-11881-13k86sp
Error: No formulae found in taps.
```

**Comment by guumaster** [comment]
It's not in the core, you need to add the tap. Try this:

`brew tap guumaster/hostctl https://github.com/guumaster/hostctl`

Then you can `brew install hostctl`

**Comment by pacodes** [comment]
brew tap works

**Comment by lethargosapatheia** [comment]
It doesn't seem to work (anymore?). Has anything changed? I added the tap and tried installing hostctl, but it still says that it cannot find the formula. Any suggestions?

**Comment by guumaster** [comment]
@lethargosapatheia  this doesn't work anymore: 
```
brew tap guumaster/hostctl https://github.com/guumaster/hostctl
```
 
Do it like this: 
```
brew install guumaster/tap/hostctl
```

No need to add the tap first.

**Comment by lethargosapatheia** [comment]
Ah, I see! Thanks a lot. And great work, it's a really helpful tool, the need had been there for a long time!
I am going to dare suggest adding the brew information on the main documentation, so that other mac users know :)

**Comment by guumaster** [comment]
It is documented [brew installation](https://guumaster.github.io/hostctl/docs/installation/#homebrew)

Please if you think there is something missing, create a new guide following [this tips](https://github.com/guumaster/hostctl/issues/44)

**Comment by lethargosapatheia** [comment]
Nothing is missing, I just didn't see it, haven't search thoroughly enough. Thank you! :)
