### ISSUE TITLE
Installation via brew

### ISSUE THREAD

**Issue by devopsbrett** [guumaster/hostctl#15]
Hi, to remain in line with other projects that provide a brew tap might I suggest creating another repo called `homebrew-tap`. This would allow you a central point for all your homebrew formulae (I hope you go on to create more projects, this one is great) as well as allowing users to install hostctl as well as subscribe to your tap with a single command `brew install guumaster/tap/hostctl`. This is the same way goreleaser does it (Gotta love a tool that "eats its own dogfood").

**Comment by guumaster** [comment]
I've created the new repo. Now I'll see how to change the Github Action to publish to it.

**Comment by devopsbrett** [comment]
Sorry, there was a slight change to my initial naming scheme. I was following the style used by github/gh but I feel the implementation used by goreleaser is better so the repo should now be called `homebrew-tap`

**Comment by guumaster** [comment]
thanks, already renamed.

**Comment by devopsbrett** [comment]
If you could leave this issue open for a little bit I'll post a gif showing the install procedure using the new repo

**Comment by guumaster** [comment]
Ok, but it's not yet working, as the workflow don't have permissions to push to the separate repo. I'm checking how to fix it.

**Comment by guumaster** [comment]
The new repo is created and populated automatically on [guumaster/homebrew-tap](https://github.com/guumaster/homebrew-tap). 

Can you try installing it from there? 

Thanks for your contribution! :tada:

**Comment by devopsbrett** [comment]
Hi @guumaster, nice work. That all seems to be working well
![hostctl](https://user-images.githubusercontent.com/4403441/77665247-4e14d180-6f77-11ea-80c5-e5972d4a8553.gif)
