### ISSUE TITLE
Minimal Output

### ISSUE THREAD

**Issue by smhmd** [guumaster/hostctl#30]
**Is your feature request related to a problem? Please describe.**
I use `/etc/hosts` to block websites during work and it exceeds 20,000 lines. When listing profiles, it all gets outputted. 

**Describe the solution you'd like**
I would love there to be a minified output flag (through persistent configuration? `hostctl config minimal`)

**Describe alternatives you've considered**
outputting to `/dev/null`, but I want to see enabled/disabled profiles.

**Comment by guumaster** [comment]
We can add a `-q` to silence output.

Also I'm thinking about a config file so users can  tweat default behavior

**Comment by smhmd** [comment]
Great. I also think a command for on/off profiles could be useful.
```fish
$ hostctl list -m
awesome on
meh off
splendid on
```
This is much easily scripted as I want to make a `dmenu` script for turning profiles on and off.

**Comment by smhmd** [comment]
effectively, `hostctl list --raw -c profile,status | uniq`.

**Comment by smhmd** [comment]
**just an idea, not really a feature request:**
How about `hostctl toggle` along side `enable` and `disable`?

**Comment by guumaster** [comment]
> ```fish
> hostctl list -m
> ```

What would be the meaning of `-m`?  menu? not sure I get it. 

The `toggle` idea could be useful

**Comment by smhmd** [comment]
the `-m` is for minimal. 

> Or even some kind of "only" to turn all off and switch to one specific profile.

I'm not sure if that's an extension of what I was alluding to. But, I agree. Different modes for enabling/disabling can be very handy.

I suggested `toggle` just to ease with the cognitive load and make use of commands from history.

Another mere suggestion and not a feature request is having `hostctl list --on`/`hostctl list --off` to list only on or off profiles.

**Comment by guumaster** [comment]
This issue ended up on this features: 

* `hostctl list enabled` to show only enabled profiles. (also works with alias `on`)
* `hostctl list disabled` to show only disabled profiles. (also works with alias `off`)
* `hostctl status` to show only one profile name per line and its status

Thanks for your contribution @smhmd!
