### ISSUE TITLE
Version flag

### ISSUE THREAD

**Issue by smhmd** [guumaster/hostctl#42]
```fish
$ hostctl -v || hostctl --version
hostctl 0.10.0
```

or add it to the output of the `help` command?

**Comment by guumaster** [comment]
implemented on v0.10.2. :+1:

**Comment by smhmd** [comment]
@guumaster 
```fish
$ hostctl -v
hostctl version dev
```
`dev` as a version is not helpful, because it'll be `dev` all the time, it seems. (this was true of `0.10.1` and is true now of `0.10.2`.)

**Comment by smhmd** [comment]
@guumaster Yes, I'm using the AUR: `yay -S hostctl`. If you wanna supply a `hostctl-bin` package, too, I would use it. Less carbon footprint.

**Comment by guumaster** [comment]
@BarbUk do you know how to pass `-ldflags` parameter to `PKGBUILD` so the build script add the proper version to the binary?

**Comment by BarbUk** [comment]
the pkgbuild is already building with -ldflags:

```
build() {
  cd $pkgname-$pkgver
  go build \
    -trimpath \
    -ldflags "-extldflags $LDFLAGS" \
    -o $pkgname .
}
```

How do you pass the version to `go build` ?

**Comment by BarbUk** [comment]
```
-X github.com/guumaster/hostctl/cmd.version=$pkgver
```

Made the change in the [pkgbuild](https://aur.archlinux.org/cgit/aur.git/commit/?h=hostctl&id=d4d8bdf01ee50a7d890367df7a8c0e1d27e7c084). 

```
❯ hostctl -v
hostctl version 1.0.2
```

**Comment by smhmd** [comment]
`hostctl -v` still outputs `hostctl version dev` on my end (installed through the AUR).

highlighted line illustrates that I have a feature only available on `1.0.8` https://github.com/guumaster/hostctl/releases/tag/v1.0.8

![image](https://user-images.githubusercontent.com/46059092/79381904-92820480-7f5a-11ea-8da6-446079ef1652.png)

**Comment by BarbUk** [comment]
Ldflags need to be updated following 007b4154c19923e1c59a53ca8d6e2ad4d471de62.

The update is available in https://aur.archlinux.org/cgit/aur.git/commit/?h=hostctl&id=42f1eed07bba06554ffb4f73a3ea9871771ba920

I did not update `pkgrel` to not break the package release automation.

@smhmd, you can reinstall the package or wait for the next release.

**Comment by BarbUk** [comment]
@guumaster, your new [commit](https://aur.archlinux.org/cgit/aur.git/commit/?h=hostctl&id=675b6dc19bba3e43086615cc5fd6063e9653face) break the version passed via ldflags.

**Comment by guumaster** [comment]
I fixed the goreleaser yml and also just updated the PKGBUILD file, can you confirm it works on Arch?

**Comment by BarbUk** [comment]
yes:

```
$ hostctl -v
hostctl version 1.0.9
```
