### ISSUE TITLE
Discussion: Interactive selection

### ISSUE THREAD

**Issue by smhmd** [guumaster/hostctl#46]
Does the framework you're using support interactivity of this sort?

![interactive](https://user-images.githubusercontent.com/46059092/79012822-24ef6600-7b5f-11ea-908d-d90190606f59.gif)

I could imagine a heavy use of `hostctl` profiles would call for such an interface.

**Comment by guumaster** [comment]
It can be done, but I'm not sure this would add much value. I'm not discarding it, but it would at the long last of the line :smile: 

I will consider if it gets some upvotes :+1:

**Comment by smhmd** [comment]
I think autocompletion and multiple profiles a command could nullify the need for such an interface. It makes for great visuals on a GIF, though :smile:. It is about the ease of use when you have a good number of profiles. I have 9 and I wouldn't survive without `xargs`.

**Comment by guumaster** [comment]
I'm closing this. With what's coming to v1.0 it won't be necessary.
