### ISSUE TITLE
Alphabetic sorting of profiles

### ISSUE THREAD

**Issue by smhmd** [guumaster/hostctl#47]
`hostctl status` gives a different sorting each time it's invoked. Could you enforce an alphabetic sorting?

This would also make names with prefixes somewhat useful if you have a good number of profiles.

**Comment by guumaster** [comment]
Yes it can be sorted. I'll add it the feature list. Probably it could be a user preference too.

**Comment by smhmd** [comment]
The alphabetic sorting is just what I came up with. If the order is consistent (by when a profile was added, for instance), that would work just as well.
