### ISSUE TITLE
Unable to handle big profile files 

### ISSUE THREAD

**Issue by smhmd** [guumaster/hostctl#53]
**Describe the bug**
I have a profile file with 23,000 lines that used to work just fine. With `1.0.0` (and now `1.0.2`), `hostctl` no longer works.
`hostctl status` didn't work. I removed all profiles to start fresh and the big file would not be `add`ed `--from`. 

**To Reproduce**
1. `sudo hostctl add nsfw --from` https://github.com/smhmd/dotfiles/blob/master/.config/hosts/nsfw `-q`
(there's an idea. Profile files `--from` URLs.)

**Expected behavior**
`hostctl` to load the profile

**System**
OS: Linux 

**Additional context**
Loading that profile worked in `0.10.x`.

**Comment by guumaster** [comment]
It does work, but it take 4 or 5 minutes if you add `-q` or not. I'll look into it.

**Comment by smhmd** [comment]
For a point of reference, it was as instantaneous as you can `cat` the file in `0.x`.

**Comment by guumaster** [comment]
fixed on [v1.0.3](https://github.com/guumaster/hostctl/tree/v1.0.3). tested with your example profile.

**Comment by guumaster** [comment]
as reference, the issue was related to the uniqueness check of domains on a profile. I removed the check for now.

**Comment by smhmd** [comment]
You can add it as a flag `-u,--uniq`?

**Comment by guumaster** [comment]
added `--uniq` to v1.0.4 :+1:
