### ISSUE TITLE
AUR package hostctl-bin

### ISSUE THREAD

**Issue by guumaster** [guumaster/hostctl#54]
@BarbUk I've notice you added this: https://aur.archlinux.org/packages/hostctl-bin/. Does it need any automation?

**Comment by BarbUk** [comment]
Yes, I was posting the news here: https://github.com/guumaster/hostctl/issues/14#issuecomment-613368980

**Comment by BarbUk** [comment]
As for the automation part, you have to call your github action a second time for the bin package.
I don't know enough about github action to be sure, be let me know if I can help.

**Comment by guumaster** [comment]
added the new step to publish binary package too. Thanks! :tada:
