### ISSUE TITLE
`--only` for `disable`

### ISSUE THREAD

**Issue by smhmd** [guumaster/hostctl#55]
for my use case, I find myself wanting to enable all profiles except one.
Could we have a `hostctl disable awesome --only`?

**Comment by guumaster** [comment]
I'll add it, although I'm not too happy with the semantics of `--only`, but I can't come up with better options.

**Comment by smhmd** [comment]
What is it that you don't like about it? Would you go for `--exact` or `--one`?

What about `hostctl enable --all [profiles]` to enable all profiles except `[profiles]`? Doing away with `--only` in the process?

```fish
$ hostctl enable awesome --all # enable all but awesome? 
```

**Comment by guumaster** [comment]
added on `v1.0.8`

**Comment by smhmd** [comment]
@guumaster out-of-date https://aur.archlinux.org/packages/hostctl-bin/

**Comment by guumaster** [comment]
fixed on v1.0.9. Thanks for reporting!
