### ISSUE TITLE
Acces denied as admin on win10

### ISSUE THREAD

**Issue by thesecmaestro** [guumaster/hostctl#6]
hostctl set -p mdserver --from c:\script\hostctl\mdserver_hosts.txt
Using hosts file: C:\Windows\System32\Drivers\etc\hosts
Error: truncate C:\Windows\System32\Drivers\etc\hosts: Access is denied.

**Comment by guumaster** [comment]
You need to run it as administrator. Same as linux, only admins have permission to edit hosts file. 

Can you confirm it works if you run it as administrator?

Thanks for reporting the issue.

**Comment by thesecmaestro** [comment]
No it does not work, i ran it as administrator as the title of the bug stated. I got the truncate error while running as administrator

**Comment by guumaster** [comment]
I've setup my windows and test it. It was too buggy. I made some fixes and now you should be able to use it. Try version v0.5.0.

I'm closing this one. Please feel free to reopen if you find anything else.

Thanks! :tada:
