### ISSUE TITLE
Display version number as part of --help

### ISSUE THREAD

**Issue by spekulatius** [guumaster/hostctl#67]
Displaying the version number as part of `--help` could help to identify issues from different versions.

**Comment by guumaster** [comment]
`cobra` generate help info automatically, but there must be a way to add version info there.

**Comment by spekulatius** [comment]
Yeah, not sure how to get it in - but would be neat to have it

**Comment by guumaster** [comment]
Oh, I think this is already included in `hostctl -v|--version` also on the _soon to be released_ `hostctl info` with a nice banner.

**Comment by spekulatius** [comment]
Oh yes. The updated version now includes the version number.
