### ISSUE TITLE
v1.1.1 - Access Denied on Windows 10 while running as administrator

### ISSUE THREAD

**Issue by Strandedpirate** [guumaster/hostctl#77]
Running a command prompt as admin and getting access denied error.

Using latest v1.1.1

My local account is in the Administrators group.

This is due to running your utility from a non-C drive; which fails. If I run it from the c:\ drive it succeeds. This is long standing bug in the GO language related to paths that is causing this. I posted about this a long time ago on another open source project. If I can find that post I'll add it here.

![image](https://user-images.githubusercontent.com/1452996/146500200-c46f7c05-83fe-44bd-9b5a-6058ba233e47.png)

**Comment by Strandedpirate** [comment]
Debugged with Visual Studio Code and the root cause of the access denied error was because Norton Antivirus detecting this program as "suspicious" and blocking it silently. oof.

Simply excluding it from Norton's block list did the trick.

**Comment by guumaster** [comment]
thanks for reporting this anyway.
